name: seg_augment

channels:
  - pytorch
  - conda-forge

dependencies:
  - pip=22.1.2
  - python=3.9.12
  - cudatoolkit=11.3
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - numpy=1.22.3
  - transformers=4.18.0
  - tokenizers=0.11.4
  - nltk=3.7
  - sentencepiece=0.1.95

  - pip:
    - fuzzywuzzy==0.18.0
    - python-Levenshtein==0.12.2
    - num2words==0.5.10
    - sacrebleu==1.5.1
    - pandas==1.4.3
    - wandb==0.13.2
    - tensorboardX==2.5.1
    - soundfile==0.10.3.post1
    - editdistance==0.6.0